### ISSUE TITLE
Internal .html links show 404 page when opened in a new tab

### ISSUE THREAD

**Issue by johnstones** [checkly/theheadless.dev#62]
On the [What is Playwright?](https://theheadless.dev/posts/basics-playwright-intro/) page, when I open the link to [What is Puppeteer?](https://theheadless.dev/posts/basics-puppeteer-intro.html) in a new tab, it shows a 404. Refreshing the page fixes the problem.

This is on line:

> The resemblance to Google's [What is Puppeteer?](https://theheadless.dev/posts/basics-puppeteer-intro.html) is striking, and for good reason.

It looks like this is something to do with the URL being postfixed with `.html` as other links on the site without this postfix don't have this problem.

**Comment by tnolet** [comment]
@johnstones thanks for filing the first bug on headless.dev 😁 @maxigimenez or @ragog will have a look
