### ISSUE TITLE
Wrong id selector on e2e-coupon

### ISSUE THREAD

**Issue by koff75** [checkly/theheadless.dev#63]
Hey,

I appreciate your work 👍  it's really useful !

Just found a little mistake on the puppeteer code in lines 24 - 25 for the e2e-coupon post:
Before : 
```
  await page.waitForSelector("#cart-img");
  await page.click("#cart-img");
```

After:
```
  await page.waitForSelector("#cart");
  await page.click("#cart");
```

Cheers

**Comment by ragog** [comment]
@koff75 good catch! should be fixed now
