### ISSUE TITLE
Cannot Reach Site (Insecure Warning from Chrome and Safari)

### ISSUE THREAD

**Issue by jimberley** [checkly/theheadless.dev#66]
I wish I could provide more information, but, the site is currently unreachable in my configuration -- it's corporate-controlled, so I have no idea what that config is. However, I get a 

```
NET::ERR_CERT_INVALID

Subject: theheadless.dev

Issuer: Cisco Umbrella Secondary SubCA nyc-SG

Expires on: Aug 22, 2020

Current date: Aug 19, 2020
```

Despite it being the 19th, I cannot access your site.

Wish I could help more.

**Comment by spartanatreyu** [comment]
I wonder if it has to do with the fact that the website uses the ".dev" TLD. We had an old cisco router that basically had a TLD whitelist, made before google stole the ".dev" TLD in 2017.

Might be worth checking if [https://web.dev](https://web.dev) and [https://web.dev](https://pika.dev) don't work either.

Can you access any other ".dev" websites?

**Comment by jimberley** [comment]
Thanks for the reply! Yeah, I can hit other .dev domains. It’s weird.

**Comment by maxigimenez** [comment]
Thanks @jimberley for flagging this, we are going to investigate and see if there's anything that we can do

**Comment by tnolet** [comment]
@maxigimenez @jimberley we host on Vercel and get our certificate from them. We can report it to them

**Comment by tnolet** [comment]
@jimberley we checked with the Vercel folks, this is not their certificate. I'm afraid your corporate firewall is playing up. I'm closing this for now.
