### ISSUE TITLE
Wait for user Login

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [checkly/theheadless.dev#73]
I am looking for an example where the script
+ Navigates to the Login page of website/application
+ Waits for the human to login into the website
+ Detects that the Login is successful
+ Takes action as programmed in the script
+ Logsout

Scripts like this can help automate tasks for people. Privacy is preserved as the script does not store/see the login credentials

**Comment by maxigimenez** [comment]
Hi @VinayaSathyanarayana, we already provide some guides of how to login, I would recommend taking a look of this https://theheadless.dev/posts/e2e-login/

**Comment by VinayaSathyanarayana** [comment]
I am looking at a scenario where the User manually (physically) types the username and password directly onto the website. The username and password are not going to be available as environment variables.

The user will physically verify whether the script has taken the person to the correct web site and then enter the username and password (and may be optionally answer a captcha) directly on the website.
