### ISSUE TITLE
Sidebar covers footer on narrower resolutions

### ISSUE THREAD

**Issue by ragog** [checkly/theheadless.dev#82]
This is more of a cosmetic thing, but on narrower resolutions the sidebar covers part of the footer, making some of the text unreadable. I was able to reproduce this on Chrome and Firefox. Screenshot below:

![Screenshot 2020-10-07 at 13 25 23](https://user-images.githubusercontent.com/12794903/95324839-9e62d980-08a0-11eb-9998-a63dc08b77ce.png)

**Comment by ndom91** [comment]
Oh there was an issue open for this already, sorry I didnt see this until now. Fixed in #90.
