### ISSUE TITLE
Navigation not working for me (in production)

### ISSUE THREAD

**Issue by chrisblanch** [checkly/theheadless.dev#85]
Steps to Reproduce:
1. Visit login page directly via link from checklyhq.com - https://theheadless.dev/tag/login/
2. Click What is Puppeteer? link in sidebar

Result:
- url updates to "https://theheadless.dev/posts/basics-puppeteer-intro/" but content does not change
- refreshing the page loads the correct content

Using Chrome 86.0.4240.111 on macOS Catalina 10.15.7

**Comment by maxigimenez** [comment]
Hi @chrisblanch, thanks for reporting this. I can reproduce the issue, there's an exception that might be related to

```
app.3c4ff2f9.js:6 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://theheadless.dev/assets/js/app.3c4ff2f9.js:6:40632)
```
